trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
 
steps:
- script: |
    # Install Python
    sudo apt update
    sudo apt install -y python3
 
    # Clone your GitHub repository
    git clone https://github.com/rainrajon/amol_demo.git
 
    # Change directory to your repository
    # cd your-repo
 
    # Run the Python script
    python3 demo_python.py
  displayName: 'Run Python Script'